version: '3'
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - ./solr/solrconfig.xml:/opt/solr/conf/solrconfig.xml
    command: 'bash -e -c "precreate-core books; cp /opt/solr/conf/solrconfig.xml /var/solr/data/books/conf/solrconfig.xml; solr-foreground;"'
